name: Full CI/CD Pipeline

on:
  push:
    branches:
      - '**'
    paths:
      - 'webapp/**'
  pull_request:
    branches:
      - '**'
    paths:
      - 'webapp/**'
  create:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'  # 請確認這是一個有效的 Node.js 版本
      - run: npm install
        working-directory: webapp/src
      - run: npm test
        working-directory: webapp/src
      - run: npm run lint
        working-directory: webapp/src

  build-and-deploy:
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, Scan and Push Docker image
        uses: docker/build-push-action@v3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-northeast-1'
      - name: Build, Scan and Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./webapp/src
          file: ./webapp/src/Dockerfile
          push: true
          tags: ${{ secrets.ECR_URL }}/my-app:${{ github.ref_name }}
          build-args:
            VERSION=${{ github.ref_name }}
          scan: true
