name: Manual Deployment to EKS

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy'
        required: true
        type: choice
        options:
          - 'v0.0.9'

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Workflow URL to Discord
        uses: nobrayner/discord-webhook@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: "A new deployment has been initiated. Approve it here: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

  deploy:
    needs: notify-discord
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
    steps:
      - name: Deploy to EKS
        run: |
          echo "Deploying to EKS..."
